services:
  backend:
    build:
      dockerfile: BeDockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./be-test2:/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/web_ide_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: web_ide_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
